metrics: event-type
Informasjonsforvaltning/fdk-mqa-url-checker pull request #27
Opened 2022-10-28 12:33 UTC by tenstad

Not really happy with a `&mut String`, but returning correct event type along with error became a hassle

2022-11-01 08:34 UTC, jeffreiffers requested changes

2022-11-01 08:34 UTC, jeffreiffers commented on src/kafka.rs
> +        &mut metric_label,
Jeg synes å bruke by reference var til dette formålet ikke pent. Kan vi ikke returnere et standard result objekt som inneholder en del metadata som vi bruker til logging/metrics?

2022-11-01 09:17 UTC, tenstad commented on src/kafka.rs
> +        &mut metric_label,
Helt enig (se description), men fant ikke noe pen måte å returnere event typen på, i både Ok og Err

2022-12-19 14:24 UTC, jeffreiffers approved these changes

2022-12-19 14:25 UTC, jeffreiffers commented
Må løse konfliktene

2023-06-05 07:56 UTC, terjesyl commented
> Kan denne lukkes, eller er den fortsatt under arbeid? :)

bump. Skal denne lukkes @jeffreiffers ?

2023-08-09 17:44 UTC, closed without merging