feat: produce assessment graphs
Informasjonsforvaltning/fdk-mqa-url-checker pull request #7
Opened 2022-06-22 10:19 UTC by tenstad

Fikser samtidig `computedOn` (kilden fremfor urlen)

2022-06-22 10:29 UTC, jeffreiffers requested changes

2022-06-22 10:29 UTC, jeffreiffers commented on src/url.rs
> +            warn!("Distribution is not a named or blank node {}", fdk_id);
```suggestion
            warn!("Distribution is not a named node {}", fdk_id);
```

2022-06-22 10:29 UTC, jeffreiffers commented on src/url.rs
>  fn check_urls(fdk_id: String, dataset_node: NamedNodeRef, store: &Store) -> Result<Store, Error> {
Skal vi fremdeles bruke fdk_id eller skulle det har vært uri?

2022-06-22 10:29 UTC, jeffreiffers commented on src/url.rs
> +            add_quality_measurement(
Vi trenger vel legge til assessment->containsQualityMeasurement?

2022-06-22 10:33 UTC, tenstad commented on src/url.rs
> +            add_quality_measurement(
Stemmer, glemte å endre `has` til `contains`. Fiksa i https://github.com/Informasjonsforvaltning/fdk-mqa-url-checker/pull/7/commits/1c15c553b3a64f98625bbcbeac4e70e7923467fc

2022-06-22 10:45 UTC, tenstad commented on src/url.rs
> +            NamedNode::new(distribution.as_str().to_string().replace("://", "://mqa."))?;
note: å erstatte slik er midlertidig. Må finne ut hvordan uri til DatasettAssessment og DistributionAssessment skal bygges opp.

2022-06-22 10:54 UTC, jeffreiffers commented on src/url.rs
> +            NamedNode::new(distribution.as_str().to_string().replace("://", "://mqa."))?;
Dette flyr ikke siden urien kan være ekstern resurs. Noe som hadde fungert er: https://fdk-mqa-assessment-api.fellesdatakatalog.digdir.no/assessments/$MD5(dataset_uri)

2022-06-22 10:54 UTC, jeffreiffers commented on src/url.rs
> +            NamedNode::new(distribution.as_str().to_string().replace("://", "://mqa."))?;
Dette flyr ikke siden urien kan være ekstern resurs. Noe som hadde fungert er: https://fdk-mqa-assessment-api.fellesdatakatalog.digdir.no/assessments/$MD5(dataset_uri)

2022-06-22 10:54 UTC, jeffreiffers commented on src/url.rs
> +            NamedNode::new(distribution.as_str().to_string().replace("://", "://mqa."))?;
Dette flyr ikke siden urien kan være ekstern resurs. Noe som hadde fungert er: https://fdk-mqa-assessment-api.fellesdatakatalog.digdir.no/assessments/$MD5(dataset_uri)

2022-06-22 10:54 UTC, jeffreiffers commented on src/url.rs
> +            NamedNode::new(distribution.as_str().to_string().replace("://", "://mqa."))?;
Dette flyr ikke siden urien kan være ekstern resurs. Noe som hadde fungert er: https://fdk-mqa-assessment-api.fellesdatakatalog.digdir.no/assessments/$MD5(dataset_uri)

2022-06-22 10:54 UTC, jeffreiffers commented on src/url.rs
> +        NamedNode::new(dataset_node.as_str().to_string().replace("://", "://mqa."))?;
Dette flyr ikke siden urien kan være ekstern resurs. Noe som hadde fungert er: https://fdk-mqa-assessment-api.fellesdatakatalog.digdir.no/assessments/$MD5(dataset_uri)

2022-06-22 10:54 UTC, jeffreiffers commented on src/url.rs
> +        NamedNode::new(dataset_node.as_str().to_string().replace("://", "://mqa."))?;
Dette flyr ikke siden urien kan være ekstern resurs. Noe som hadde fungert er: https://fdk-mqa-assessment-api.fellesdatakatalog.digdir.no/assessments/$MD5(dataset_uri)

2022-06-22 12:23 UTC, tenstad commented on src/url.rs
> +            NamedNode::new(distribution.as_str().to_string().replace("://", "://mqa."))?;
Fiksa i https://github.com/Informasjonsforvaltning/fdk-mqa-url-checker/pull/7/commits/15716034cda53680646fa59b6708eb0cea61095d

2022-06-22 12:23 UTC, tenstad commented on src/url.rs
> +        NamedNode::new(dataset_node.as_str().to_string().replace("://", "://mqa."))?;
Se https://github.com/Informasjonsforvaltning/fdk-mqa-url-checker/pull/7#discussion_r903583362

2022-06-22 12:23 UTC, tenstad commented on src/url.rs
> +        NamedNode::new(dataset_node.as_str().to_string().replace("://", "://mqa."))?;
Se https://github.com/Informasjonsforvaltning/fdk-mqa-url-checker/pull/7#discussion_r903583362

2022-06-23 06:58 UTC, jeffreiffers approved these changes

2022-06-23 07:01 UTC, jeffreiffers requested changes

2022-06-23 07:01 UTC, jeffreiffers commented on src/vocab.rs
> +        NamedNodeRef::new_unchecked("http://www.w3.org/ns/dqv#containsQualityMeasurement");
Det er ikke dqv men dcatno-mqa prefix

2022-06-23 07:02 UTC, jeffreiffers requested changes

2022-06-23 07:02 UTC, jeffreiffers commented on src/vocab.rs
> +        NamedNodeRef::new_unchecked("http://www.w3.org/ns/dcat#assessmentOf");
feil prefix

2022-06-23 07:11 UTC, jeffreiffers approved these changes

2022-06-23 07:23 UTC, tenstad commented
Nå er ikke funksjonen så lang lenger @jeffreiffers https://github.com/Informasjonsforvaltning/fdk-mqa-url-checker/pull/7/commits/819c68e5a783d8c7e9e7298ca8eaab071d54e1b5

2022-06-23 12:52 UTC, merged